gpu_id: '0'
log_wandb: false
seed: 42
model: DTMFRec         # 替换为改进后的模型名称

hidden_size: 64
num_layers: 1
dropout_prob: 0.32
loss_type: CE

d_state: 32
d_conv: 4
expand: 2
temperature: 0.15

# ==================================
# ml-1m
# ==================================
#dataset: ml-1m
#MAX_ITEM_LIST_LENGTH: 200

#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: item_id
#TIME_FIELD: timestamp
#RATING_FIELD: rating
#load_col:
#  inter: [ user_id, item_id, rating, timestamp ]
#user_inter_num_interval: "[5,inf)"
#item_inter_num_interval: "[5,inf)"
#filter_inter_by_user_or_item: true

# ==================================
# yelp
# ==================================
#dataset: yelp2022
#MAX_ITEM_LIST_LENGTH: 100
#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: item_id
#TIME_FIELD: timestamp
#RATING_FIELD: rating
#load_col:
#  inter: [ user_id, item_id, rating, timestamp ]
#user_inter_num_interval: "[5,100)"
#item_inter_num_interval: "[5,100)"
#filter_inter_by_user_or_item: true

#ITEM_ID_FIELD: business_id
#TIME_FIELD: date
#RATING_FIELD: stars
#load_col:
#  inter: [user_id, business_id, stars, date]

dataset: amazon-beauty
MAX_ITEM_LIST_LENGTH: 50
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
  inter: [ user_id, item_id, rating, timestamp ]
NEG_PREFIX: neg_
LABEL_FIELD: label
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
POSITION_FIELD: position_id
user_inter_num_interval: "[5,inf)"  s
item_inter_num_interval: "[5,inf)"
#filter_inter_by_user_or_item: true

# ==================================
# train
# ==================================
epochs: 200
train_batch_size: 2048
eval_batch_size: 4096
learner: adam
learning_rate: 0.0025
weight_decay: 0.0
eval_step: 1
stopping_step: 10
metrics: [ 'Hit', 'NDCG', 'MRR' ]
valid_metric: NDCG@10
topk: [ 10 ]

train_neg_sample_args: ~


